version: '3.1'

services:
  db:
    image: postgres
    network_mode: host
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    volumes:
      - ./scripts/init.pgsql:/docker-entrypoint.d/init.sql
  db-admin:
    image: dpage/pgadmin4
    network_mode: host
    restart: always
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@resev.com
      PGADMIN_DEFAULT_PASSWORD: dev